import Head from 'next/head'
import { GetServerSidePropsContext } from 'next'

import BasicLayout from '@/components/layouts/BasicLayout'
import LoginForm from '@/components/authentication/LoginForm'

import nookies from 'nookies'
import { verifyIDToken } from '@/config/firebaseadmin'


export default function Login() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicLayout>
         <div className='h-full flex flex-col items-center justify-center'>
            <h1>Login</h1>
            <LoginForm/>
         </div>
      </BasicLayout>
    </>
  )
}

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  try {
    const cookies = nookies.get(ctx)
    const token = await verifyIDToken(cookies.token)

    if (token)
      return {
        redirect: {destination: '/'}
      }
     
    return {
      props: {}
    }

  } catch(err) {
      return {
        props: {}
      }
  }
}