import Head from 'next/head'

import BasicLayout from '@/components/layouts/BasicLayout'
import BarGraph from '@/components/reports/BarGraph'
import FinanceOverview from '@/components/reports/FinanceOverview'
import PieChart from '@/components/reports/PieChart'
import SpendingOverview from '@/components/reports/SpendingOverview'

import nookies from 'nookies'
import { verifyIDToken } from '@/config/firebaseadmin'
import { GetServerSidePropsContext } from 'next'
import { doc, getDoc } from 'firebase/firestore'
import { db } from '@/config/firebase'


export default function Transactions() {
  return (
    <>
      <Head>
        <title>Reports</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BasicLayout>
         <h1>Reports</h1>

         <div className="flex flex-col gap-2 h-max rounded-md bg-secondary-dark/[50%] shadow-md p-2">
            <h2 className="bg-primary-dark py-2 px-4 rounded-md shadow-label w-fit text-extra-light">Finances</h2>
            <div className='h-[12rem] w-[75%] sm-width:w-full mx-auto'>
               <BarGraph/>
            </div>
            <FinanceOverview/>
         </div>

         <div className="flex flex-col gap-2 h-max rounded-md bg-secondary-dark/[50%] shadow-md p-2">
            <h2 className="bg-primary-dark py-2 px-4 rounded-md shadow-label w-fit text-extra-light">Spending</h2>
            <div className="w-full flex flex-col">
               <PieChart/>
               <SpendingOverview/>
            </div>
         </div>
      </BasicLayout>
    </>
  )
}

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
   try {
      const cookies = nookies.get(ctx)
      const token = await verifyIDToken(cookies.token)

      const linkref = doc(db, `users/${token.uid}/linkBankAcc`, 'linkBankAccInfo')
      const linkSnap = await getDoc(linkref)

      if (!linkSnap.exists())
         return {
            redirect: {destination: '/link-bank-account'}
         }
      
      return {
       props: {}
    }
 
   } catch(err) {
       return {
         redirect: {destination: '/login'}
       }
   }
}